### ISSUE TITLE
status of dopy?

### ISSUE THREAD

**Issue by kontrafiktion** [devo-ps/dopy#22]
It looks like "dopy" is not really alive anymore.
Shall we do an "official" fork? Could another committer be added?

**Comment by zbal** [comment]
Dopy is alive and well ;) but not so active indeed ... It started as a need about 2 years ago but the code is kinda crap and I'd rather go for a revamp keeping compatibility than anything else. If you are interested in being a committer I can add you. Let me know.

**Comment by kontrafiktion** [comment]
Hi!
I am rather a Python noob, so perhaps not the guy you need.
I am happy that everything outstanding pull request is merged, so my immediate need is met. I am willing to help, but I wouldn't know where to start "revamping" anything.

**Comment by kontrafiktion** [comment]
Hi Vincent!

Getting back to you after some time.
There are three oustanding pull requests, I am mostly interested in getting

	https://github.com/Wiredcraft/dopy/pull/48 <https://github.com/Wiredcraft/dopy/pull/48> 

merged.

So please either do it yourself, or if you are really tired of taking care of dopy, please make me committer.

Kind Regards
Victor
