### ISSUE TITLE
Cannot create domain record with V2 API

### ISSUE THREAD

**Issue by mbugeia** [devo-ps/dopy#23]
https://github.com/devo-ps/dopy/blob/master/dopy/manager.py#L362

In V2, DO API return a "domain_record" json object, not "record" as in V1, see: https://developers.digitalocean.com/documentation/v2/#domain-records

Other domain record functions are ok.

**Comment by KarelJakubec** [comment]
Hi @mbugela and @zbal,
any chance to merge this soon? I run into this problem today as well...

Thanks,
Karel

**Comment by mbugeia** [comment]
Hi @zbal,
I really want this to be merged too, the feature is broken right now.
Thanks

**Comment by certifiedloud** [comment]
+1

**Comment by zbal** [comment]
Hi guys - just merged - will push the change to pypi today. Thanks for the PR!
