### ISSUE TITLE
Version 0.3.5 changes argument order for private networking

### ISSUE THREAD

**Issue by leucos** [devo-ps/dopy#27]
In commit c240b361db580b0a5bb604d9c65572b1b33026d5, `ipv6` argument has been inserted between `virtio` and `private_networking`.

This breaks downstream code when named arguments are not used (e.g. ansible's digital_ocean module).

**Comment by zbal** [comment]
Thanks, good catch - fixed and pushed to pip v. 0.3.6

**Comment by leucos** [comment]
Tested => :+1: 
Thanks a lot @zbal. Notified ansible/ansible-modules-core.
